# Generated by Django 4.2.6 on 2023-10-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatastroEquipoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio_clinico', models.CharField(max_length=200)),
                ('recinto', models.CharField(max_length=100)),
                ('clase', models.CharField(max_length=100)),
                ('subclase', models.CharField(max_length=100)),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100)),
                ('numero_inventario', models.IntegerField()),
                ('anio_adquisicion', models.IntegerField()),
                ('vida_util', models.IntegerField()),
                ('vida_util_residual', models.IntegerField()),
                ('propio', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('garantia', models.CharField(max_length=2)),
                ('anio_vencimiento_garantia', models.IntegerField()),
                ('bajo_plan_mantenimiento', models.CharField(max_length=2)),
            ],
        ),
    ]
