# Generated by Django 4.2.6 on 2023-11-04 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcatastro', '0003_alter_catastroequipomedico_anio_adquisicion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CatastroEquipoMedico',
            new_name='CatastroEquipoIndustriales',
        ),
    ]
