# Generated by Django 4.2.6 on 2023-11-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcatastro', '0004_rename_catastroequipomedico_catastroequipoindustriales'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatastroEquiposMedicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=100)),
                ('sub_ubicacion', models.CharField(max_length=100)),
                ('clase', models.CharField(max_length=50)),
                ('sub_clase', models.CharField(max_length=70)),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100)),
                ('numero_inventario', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('vida_util', models.IntegerField()),
                ('propietario', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('criticidad', models.CharField(max_length=100)),
                ('garantia', models.IntegerField()),
                ('vencimiento_garantia', models.CharField(max_length=100)),
                ('plan_mantencion', models.CharField(max_length=100)),
                ('tipo_equipo', models.CharField(max_length=100)),
                ('id_convenio', models.IntegerField()),
                ('id_institucion', models.IntegerField()),
                ('eliminado', models.IntegerField()),
            ],
        ),
    ]
