# Generated by Django 4.2.6 on 2023-11-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcatastro', '0005_catastroequiposmedicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catastroequiposmedicos',
            name='plan_mantencion',
            field=models.IntegerField(),
        ),
    ]
