# Generated by Django 4.2.6 on 2023-11-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcatastro', '0006_alter_catastroequiposmedicos_plan_mantencion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatastroAmbulancias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=100)),
                ('sub_ubicacion', models.CharField(max_length=100)),
                ('carroceria', models.CharField(max_length=100)),
                ('clase', models.CharField(max_length=50)),
                ('samu', models.CharField(max_length=4)),
                ('funcion', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('patente', models.CharField(max_length=50)),
                ('numero_motor', models.CharField(max_length=100)),
                ('kilometraje', models.IntegerField()),
                ('propietario', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('vida_util', models.IntegerField()),
                ('criticidad', models.CharField(max_length=100)),
                ('garantia', models.IntegerField()),
                ('vencimiento_garantia', models.CharField(max_length=100)),
                ('plan_mantencion', models.IntegerField()),
                ('tipo_equipo', models.CharField(max_length=100)),
                ('id_convenio', models.IntegerField()),
                ('id_institucion', models.IntegerField()),
                ('eliminado', models.IntegerField()),
            ],
        ),
    ]
