# Generated by Django 4.2.6 on 2023-11-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcatastro', '0008_alter_catastroequiposmedicos_anio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catastroequipoindustriales',
            name='id_institucion',
            field=models.IntegerField(null=True),
        ),
    ]
