# Generated by Django 4.2.6 on 2023-11-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcatastro', '0009_catastroequipoindustriales_id_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catastroequipoindustriales',
            name='anio_adquisicion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='catastroequipoindustriales',
            name='anio_vencimiento_garantia',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='catastroequipoindustriales',
            name='bajo_plan_mantenimiento',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='catastroequipoindustriales',
            name='clase',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='catastroequipoindustriales',
            name='estado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='catastroequipoindustriales',
            name='garantia',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='catastroequipoindustriales',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='catastroequipoindustriales',
            name='modelo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='catastroequipoindustriales',
            name='nombre_equipo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='catastroequipoindustriales',
            name='numero_inventario',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='catastroequipoindustriales',
            name='propio',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='catastroequipoindustriales',
            name='recinto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='catastroequipoindustriales',
            name='serie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='catastroequipoindustriales',
            name='servicio_clinico',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='catastroequipoindustriales',
            name='subclase',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='catastroequipoindustriales',
            name='vida_util',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='catastroequipoindustriales',
            name='vida_util_residual',
            field=models.IntegerField(null=True),
        ),
    ]
