# Generated by Django 4.2.6 on 2023-11-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcatastro', '0010_alter_catastroequipoindustriales_anio_adquisicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catastroequipoindustriales',
            name='garantia',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
