# Generated by Django 4.2.6 on 2023-11-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcatastro', '0011_alter_catastroequipoindustriales_garantia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catastroequipoindustriales',
            name='bajo_plan_mantenimiento',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
