# Generated by Django 4.2.6 on 2023-12-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcatastro', '0012_alter_catastroequipoindustriales_bajo_plan_mantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catastroambulancias',
            name='kilometraje',
            field=models.PositiveIntegerField(),
        ),
    ]
