# Generated by Django 4.2.6 on 2023-12-09 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcatastro', '0014_remove_catastroambulancias_carroceria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catastroambulancias',
            old_name='establecimineto',
            new_name='establecimiento',
        ),
    ]
