# Generated by Django 4.2.6 on 2023-12-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcatastro', '0016_alter_catastroambulancias_garantia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catastroambulancias',
            name='id_convenio_mantenimiento',
            field=models.CharField(max_length=150),
        ),
    ]
