# Generated by Django 4.2.6 on 2023-12-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcatastro', '0018_alter_catastroambulancias_costo_anual_mantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catastroambulancias',
            name='costo_anual_mantenimiento',
            field=models.IntegerField(default=0),
        ),
    ]
