# Generated by Django 4.2.6 on 2023-12-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcatastro', '0019_alter_catastroambulancias_costo_anual_mantenimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catastroequiposmedicos',
            name='numero_inventario',
        ),
        migrations.RemoveField(
            model_name='catastroequiposmedicos',
            name='propietario',
        ),
        migrations.RemoveField(
            model_name='catastroequiposmedicos',
            name='sub_clase',
        ),
        migrations.RemoveField(
            model_name='catastroequiposmedicos',
            name='sub_ubicacion',
        ),
        migrations.RemoveField(
            model_name='catastroequiposmedicos',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='catastroequiposmedicos',
            name='anio_ingreso',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='catastroequiposmedicos',
            name='costo_anual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='catastroequiposmedicos',
            name='nombre_proveedor',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='catastroequiposmedicos',
            name='numero_serie',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='catastroequiposmedicos',
            name='recinto',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='catastroequiposmedicos',
            name='servicio_clinico',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='catastroequiposmedicos',
            name='subclase',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='catastroequiposmedicos',
            name='tipo_mantenimiento',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='catastroequiposmedicos',
            name='vida_util_residual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='catastroequiposmedicos',
            name='anio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='catastroequiposmedicos',
            name='clase',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='catastroequiposmedicos',
            name='criticidad',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='catastroequiposmedicos',
            name='eliminado',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='catastroequiposmedicos',
            name='estado',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='catastroequiposmedicos',
            name='garantia',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='catastroequiposmedicos',
            name='id_convenio',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='catastroequiposmedicos',
            name='id_institucion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='catastroequiposmedicos',
            name='marca',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='catastroequiposmedicos',
            name='modelo',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='catastroequiposmedicos',
            name='nombre',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='catastroequiposmedicos',
            name='plan_mantencion',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='catastroequiposmedicos',
            name='serie',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='catastroequiposmedicos',
            name='tipo_equipo',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='catastroequiposmedicos',
            name='vencimiento_garantia',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='catastroequiposmedicos',
            name='vida_util',
            field=models.IntegerField(default=0),
        ),
    ]
