# Generated by Django 4.2.6 on 2023-12-10 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcatastro', '0020_remove_catastroequiposmedicos_numero_inventario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catastroequiposmedicos',
            old_name='numero_serie',
            new_name='numero_inventario',
        ),
    ]
