# Generated by Django 4.2.6 on 2023-12-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcatastro', '0022_remove_catastroequipoindustriales_anio_adquisicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catastroequipoindustriales',
            name='id_convenio_mantenimiento',
            field=models.CharField(default='', max_length=150),
        ),
    ]
