# Generated by Django 4.2.6 on 2023-10-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ciudad', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=200)),
            ],
        ),
    ]
