# Generated by Django 4.2.6 on 2023-12-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinstituciones', '0003_rename_fecha_expiracion_convenio_convenios_fecha_expiracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenios',
            name='id_institucion',
            field=models.IntegerField(default=0),
        ),
    ]
