# Generated by Django 4.2.6 on 2023-12-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinstituciones', '0005_alter_convenios_fecha_expiracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenios',
            name='tipo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
