# Generated by Django 4.2.6 on 2023-12-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinstituciones', '0006_convenios_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenios',
            name='monto_anual',
            field=models.BigIntegerField(),
        ),
    ]
