# Generated by Django 4.2.6 on 2023-10-29 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appinstituciones', '0001_initial'),
        ('appautenticacion', '0002_customuser_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='institucion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appinstituciones.institucion'),
        ),
    ]
