# Generated by Django 4.2.6 on 2023-12-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appautenticacion', '0005_alter_customuser_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rut',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
